spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: QhrtnswoTkddl1!6
    url: jdbc:mysql://localhost:3306/nawa
server:
  port: 8081

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true


  # JSP ?? ??,, MYBATIS ??